# -*- coding: utf-8 -*-
# Blocchi del Manuale di volo v3 (18 pagine, 7 settembre 2026).
# kind = etichetta del ruolo nel layout. Prefisso "Vincolo|" = blocco di compliance.
P = [
("01","Copertina","Facciamo un video insieme.",[
 ("Titolo","Facciamo un video insieme."),
 ("Promessa","La tua giornata, le tue parole, e Giada che risponde."),
 ("Fumetto","Ciao! Sono Giada. Com’è andata oggi?"),
 ("Sticker","TUTTO PARTE DA UN’IDEA TUA · CIAO! · PROVA. GIOCA. RACCONTA."),
 ("Immagine","Pannello periwinkle con l’avatar di Giada. In attesa della scena nuova: Giada che si registra un video selfie col telefono (giada-selfie-scene.png)."),
]),
("02","Ciao","Ciao, sono Andrea.",[
 ("Titolo","Ciao, sono Andrea."),
 ("Presentazione","In Vivarium mi occupo di marketing e contenuti. Giada la conosci fra due pagine: vive su Telegram e risponde davvero. Questo programma nasce da una cosa semplice: i video migliori li fa chi la usa e ha qualcosa da dire."),
 ("Patto","Non è un contest e non è UGC a cottimo. Un video alla volta, con calma. Io ti porto obiettivi, riferimenti e i pochi limiti che abbiamo; l’idea, le parole e il taglio restano tuoi."),
 ("Chiusa","Le idee le leggo io, una per una. Qui dentro c’è quello che darei a me stesso per cominciare."),
 ("Mappa","La tua mappa — 03 Conosci e prova Giada · 05 Trova la tua storia · 06 Esempi e come si gira · 13 Regole e consegna"),
 ("Sticker","18 PAGINE. DIECI MINUTI."),
]),
("03","Conosci Giada","Un’amica in chat. Sempre a un messaggio di distanza.",[
 ("Titolo","Un’amica in chat. Sempre a un messaggio di distanza."),
 ("Intro","Vive su Telegram. Le scrivi, le mandi la foto del piatto o un vocale mentre cammini. Le puoi raccontare anche acqua, movimento, sonno e peso: quello che le dici, se lo tiene."),
 ("Funzione 1","Capire il pasto — Le mandi la foto e ti dice cosa c’è dentro: calorie, macro e se va d’accordo con i tuoi obiettivi."),
 ("Funzione 2","Decidere cosa mangiare — «Ho questo in frigo, che faccio?» Lei tira fuori un’idea, non una lezione di cucina."),
 ("Funzione 3","Ricordarsi di te — Non riparte da zero ogni volta: sa com’è andata la settimana e ti aiuta a riprendere dopo uno sgarro, senza prediche."),
 ("Funzione 4","Uscire senza pensieri — Al ristorante le mandi il menù e sceglie con te. E se ti muovi, tiene il conto anche di quello."),
]),
("04","Prova Giada","Prima la chat. Poi la scintilla.",[
 ("Titolo","Prima la chat. Poi la scintilla."),
 ("Intro","Nei tuoi 14 giorni di prova usala davvero: niente compiti da consegnare, scrivile come scriveresti a un’amica. La tua chat vera è il materiale del video."),
 ("Sezione","Quattro modi per rompere il ghiaccio"),
 ("Spunto 1","«Cosa preparo con quello che ho in frigo?»"),
 ("Spunto 2","«Stasera mangio qui: mi dai un’idea dal menù?»"),
 ("Spunto 3","«Oggi è andata così. Come riprendo il filo?»"),
 ("Spunto 4","Una foto del piatto, senza scrivere niente."),
 ("Vincolo|CTA","Inizia i tuoi 14 giorni → https://t.me/giadacare_bot?start=ad_creatorsb2b_t14d (bottone + QR, stesso link)"),
 ("Nota","Prenditi i primi due giorni per giocarci: le idee arrivano da lì."),
]),
("05","A chi parli","A chi stai parlando? Scegline una sola.",[
 ("Titolo","A chi stai parlando? Scegline una sola."),
 ("Intro","Queste sono le persone che scrivono a Giada ogni giorno. Non sono caselle: servono a darti un volto preciso in testa mentre scrivi."),
 ("Persona 01","La testa già piena — «Non ho voglia di pensarci anche a questo.» Le arrivi se le mostri che bastano dieci secondi e una foto."),
 ("Persona 02","Il piano c’è, la costanza no — «So cosa fare. Il difficile è farlo ogni giorno.» Le arrivi se fai vedere una giornata storta che si raddrizza."),
 ("Persona 03","Vuole una risposta, non una lezione — «Chiedo una cosa e mi ritrovo un trattato.» Le arrivi se mostri Giada che risponde corta e chiara."),
 ("Persona 04","I passi sì, il pranzo no — «Misuro tutto, tranne quello che mangio.» Le arrivi se colleghi il movimento a quello che c’è nel piatto."),
 ("Persona 05","Il solito «da lunedì» — «Non voglio ricominciare da capo un’altra volta.» Le arrivi se il tuo video non parte da una colpa."),
 ("Nota","Sono spunti, non recinti: scegli quella che conosci meglio e parla solo a lei."),
]),
("06","Esempi","Cosa abbiamo già fatto.",[
 ("Titolo","Cosa abbiamo già fatto."),
 ("Intro","Sei video girati con altre creator. Non devi rifarli: guardali per capire cosa ha funzionato e prendi l’idea che ti serve."),
 ("Card 1","ROSA 2 · 35,4 s — Poche scene, tanta luce. Ha funzionato perché in trenta secondi si capisce tutto: colazione e chat grande."),
 ("Card 2","ELENA 2 · 78,1 s — Un elenco che tiene incollati. Ha funzionato perché dice cosa farà e poi lo fa: sai sempre cosa sta per succedere."),
 ("Card 3","MARIA 1 · 55,1 s — Un dubbio vero, detto a voce. Ha funzionato perché la domanda se la fanno tutti, e la risposta arriva in scena."),
 ("Card 4","MARIA 2 · 55,9 s — Si legge la conversazione. Ha funzionato perché la chat riempie lo schermo: Giada si capisce senza spiegarla."),
 ("Nota","Ispirazione, mai copia: prendi l’idea, non le stesse inquadrature."),
]),
("07","Esempi","Altri due, girati in modo diverso.",[
 ("Titolo","Altri due, girati in modo diverso."),
 ("Intro","Rosa porta la giornata dentro il video."),
 ("Card 1","ROSA 1 · 65,2 s — Una giornata raccontata. Allenamento, piatti, luoghi veri: Giada entra nella quotidianità senza essere annunciata. Ha funzionato: la logica del vlog, scegli un momento vicino a chi ti guarda e falla entrare lì."),
 ("Card 2","ELENA 1 · 61,5 s — Una domanda in mano. Tiene il telefono con la domanda in vista e la legge ad alta voce, mentre cammina. Ha funzionato: il gesto e le parole dicono la stessa cosa, si capisce anche senza audio."),
 ("Nota","Anche qui: ispirazione, mai copia. Il taglio è tuo."),
]),
("08","Scrivi l’idea","Cosa deve fare il tuo video.",[
 ("Titolo","Cosa deve fare il tuo video."),
 ("Intro","Prima esce sul tuo profilo, come reel o TikTok. Se funziona, lo portiamo anche in campagna. Quindi gira quello che pubblicheresti comunque."),
 ("Mossa 1","Ferma lo scroll — Primi tre secondi: una situazione precisa, un gesto, una domanda."),
 ("Mossa 2","Fai vedere Giada — Falla entrare almeno una volta. Ingrandisci la chat: chi guarda deve poterla leggere."),
 ("Mossa 3","Lascia un invito — Uno solo, detto con calma: «Provala gratis dal link»."),
 ("Riquadro","Perché uno resta fino alla fine: SI RICONOSCE · VUOLE SAPERE COM’È FINITA · SE LO SALVA · PIACE COME LO RACCONTI TU"),
]),
("09","Scrivi l’idea","Uno script che respira.",[
 ("Titolo","Uno script che respira."),
 ("Intro","Inizio, centro, fine. In 30-90 secondi apri una domanda, fai arrivare la risposta e chiudi il cerchio. Scrivi a blocchi: per ogni frase scegli anche cosa si vede."),
 ("Chip","01 Apri una domanda · 02 Fai arrivare la risposta · 03 Chiudi il cerchio"),
 ("Script HOOK","A: «Stasera ceno fuori: il menù lo apro prima.» — B: «Frigo mezzo vuoto e zero idee.»"),
 ("Script COSTRUZIONE","A: «Mando il menù a Giada e le chiedo cosa prendo.» — B: «Le mando la foto di quello che c’è dentro.»"),
 ("Script PAYOFF","A: Leggi ad alta voce la sua risposta sul menù. — B: Fai la ricetta che ti ha tirato fuori."),
 ("Script CTA","A: «La provi gratis dal link.» — B: «Se ti va, provala anche tu.»"),
 ("Nota","Due strade, non due modelli. La terza, la tua, è la migliore."),
]),
("10","Il primo fotogramma","Fermare lo scroll. Senza urlare.",[
 ("Titolo","Fermare lo scroll. Senza urlare."),
 ("Intro","Otto forme che funzionano. Una sola per video: scrivine tre su un foglio e tieni quella che regge."),
 ("Hook 01","La domanda sul piatto — Inquadri il pranzo dall’alto: «Secondo te cosa manca?» Chi guarda risponde nella testa, e resta."),
 ("Hook 02","L’oggetto fuori posto — Il menù di un ristorante appoggiato tra i pesi in palestra. Una cosa che non c’entra incuriosisce e apre la storia."),
 ("Hook 03","Due cose a confronto — Da una parte i passi contati, dall’altra i pasti mai raccontati. Il confronto è tra abitudini, mai tra corpi."),
 ("Hook 04","La negazione — «Oggi non conto niente a mente.» Dire cosa non farai incuriosisce: poi mostri subito il gesto al posto suo."),
 ("Hook 05","Il quiz — «Secondo te cosa le ho chiesto?», e si vede solo la risposta. Chi guarda vuole scoprire la domanda."),
 ("Hook 06","La scena che conosci — Frigo aperto, sguardo dentro: «E adesso?» Nessuna presentazione: si riconosce da sola."),
 ("Hook 07","La parola gigante — «CENA?» scritto grande sopra una scena vera. Una parola sola tiene lo sguardo, poi arriva la prova."),
 ("Hook 08","L’immagine che spiega — La lista delle cose da fare che si allunga da sola. Rende visibile un peso che di solito si racconta a parole."),
]),
("11","Formato e montaggio","Il tuo taglio. Tre passate.",[
 ("Titolo","Il tuo taglio. Tre passate."),
 ("Intro","Volto e voce, voice-over, mani, cibo, schermo registrato: il formato lo scegli tu."),
 ("Formati","Chat protagonista · Problema, poi soluzione · Titolo da notizia · Risposta a un commento · Esperienza personale · Giornata / backstage"),
 ("Passata 01","Niente vuoti — Dove non parli, di solito non serve: lascia respirare la voce e taglia il resto."),
 ("Passata 02","Fidati della noia — Se ti annoi mentre lo riguardi, quel pezzo lo sente anche chi guarda: accorcia lì."),
 ("Passata 03","Cambia ogni 3-5 secondi — Uno zoom, un cambio di inquadratura, la chat che compare: sono questi a tenere su lo sguardo."),
 ("Nota","Riguardalo una volta col telefono in mano, come lo guarderebbe lei."),
]),
("12","Audio e sottotitoli","Prima si sente. Poi si legge.",[
 ("Titolo","Prima si sente. Poi si legge."),
 ("Audio","L’audio conta più dell’immagine. Registra vicino al microfono, in una stanza che non rimbomba, e riascoltati prima di montare: se la voce è pulita, il resto si perdona."),
 ("Vincolo|Musica","La musica, libera davvero — Meglio evitare gli audio di tendenza presi dai social: la licenza deve coprire anche la pubblicità e tutti i canali. Una libreria free va benissimo."),
 ("Sottotitoli","Sottotitoli sempre. Lo stile è tuo. L’unica cosa che ti chiediamo: due o tre parole per volta, anche una sola. Servono a dare ritmo, non a trascrivere. Font, colore e animazione li scegli tu."),
 ("Demo","LA TUA · CHAT · SI LEGGE — tre battute, tre respiri: è quello che tiene il ritmo."),
 ("Nota","Se il tuo montaggio le fa apparire una parola per volta, ancora meglio."),
]),
("13","Le regole tecniche","La scheda da tenere a vista.",[
 ("Titolo","La scheda da tenere a vista."),
 ("Riquadri","9:16 verticale · 30-90 secondi"),
 ("Tabella","Lingua: italiano, il tuo. Strumenti: quelli che usi già, per girare e montare. Audio: la voce prima di tutto. Sottotitoli: sempre, con lo stile che preferisci. Giada: almeno un momento, con la chat leggibile. File: finito, senza watermark dell’app di montaggio. Invio: Drive o WeTransfer, il grezzo tienilo tu. Tempi: 7-10 giorni dalla call, senza corse. Revisione: al massimo una, se funziona nessuna."),
 ("Nota","La prima volta è un video solo. Il resto lo decidiamo insieme."),
]),
("14","Cosa non si può dire","Creatività sì. Promesse magiche no.",[
 ("Titolo","Creatività sì. Promesse magiche no."),
 ("Vincolo|Divieto","Niente chili, taglie o percentuali. Non promettiamo risultati sul corpo. I numeri veri del percorso, quelli sì: giorni, pasti raccontati, abitudini."),
 ("Vincolo|Divieto","Niente primi piani su una parte del corpo. Non pizzicare il grasso, non usare il corpo come il problema da correggere."),
 ("Vincolo|Divieto","Nessuno deve sentirsi sbagliato. Vale anche per te: «ero uno schifo» non ci va, nemmeno detto ridendo."),
 ("Vincolo|Divieto","Mai «sei sola». La solitudine non si usa come leva. Fai vedere che Giada risponde: basta quello."),
 ("Vincolo|Divieto","Si capisce che Giada è un’AI. Dillo con le tue parole, dove ti viene meglio: chi guarda deve capire che è un’AI su Telegram, non una persona in carne e ossa."),
 ("Vincolo|Divieto","Giada non è un medico né una nutrizionista. Non fa diagnosi, non cura, non scrive diete, e le sue stime sono indicative. Niente condizioni cliniche nel video."),
 ("Nota","Il resto è tuo: racconta quello che hai provato davvero."),
]),
("15","Cosa non si mostra","Un ultimo sguardo prima di esportare.",[
 ("Titolo","Un ultimo sguardo prima di esportare."),
 ("Vincolo|01","Solo la chat con Giada — Prima di registrare lo schermo dai un’occhiata: niente lista chat, nomi o notifiche di altri."),
 ("Vincolo|02","Nessun altro marchio in campo — Maglietta, confezioni, sfondo. E niente watermark delle app di montaggio."),
 ("Vincolo|03","Niente minori — Se nel video c’è un altro adulto serve il suo ok, e te ne prendi la responsabilità."),
 ("Vincolo|04","Niente audio dei trend — Prendi la musica da una libreria libera, con licenza valida anche per la pubblicità."),
 ("Nota","E l’ordine, che aiuta tutti: prima l’idea, poi ci sentiamo, poi si gira."),
]),
("16","Come si va avanti","La tua idea arriva qui.",[
 ("Titolo","La tua idea arriva qui."),
 ("Indirizzo","andrea@vivariumai.co (bolla teal, cliccabile)"),
 ("Intro","Mandami lo script e due indicazioni visive in un documento, oppure un video-selfie: dimmi a chi parli, che scena hai in testa, come apri e cosa si vede di Giada. Con calma, non c’è una scadenza."),
 ("Step 01","Ti rispondo entro 72 ore — Un riscontro vero: cosa mi piace, cosa cambierei, e se serve ci facciamo una call breve."),
 ("Step 02","Se l’idea ci piace, ci parliamo — Mezz’ora per allineare taglio, compenso e dettagli. Poi hai mano libera."),
 ("Step 03","Giri, e poi mi mandi il video — Finito entro 7-10 giorni dalla call, via Drive o WeTransfer. Al massimo una revisione."),
]),
("17","Il compenso","Facciamo i conti insieme.",[
 ("Titolo","Facciamo i conti insieme."),
 ("Compenso","da 50€ per ogni video selezionato. È UN PAVIMENTO, NON UN TETTO."),
 ("Diritti","Nessuna esclusiva: continui a lavorare con chi vuoi, prima e dopo."),
 ("Upside","Cosa può far salire la cifra — Un hook in più, un pacchetto di video, una collaborazione che va avanti nei mesi. E se hai numeri tuoi da mostrare, possiamo ragionare anche sui risultati."),
 ("Riquadro","Ne parliamo in call, prima che tu giri. Due hook vogliono dire due video finiti, con visivi diversi. Fattura o ritenuta d’acconto: vediamo lì cosa è più comodo per te."),
]),
("18","Ora tocca a te","Ultimo check. Poi tocca a te.",[
 ("Titolo","Ultimo check. Poi tocca a te."),
 ("Checklist","Parlo a una persona sola, e si sente · L’apertura e il finale si tengono insieme · Giada si vede e la chat si legge · Si capisce che è un’AI · Voce pulita, sottotitoli corti · Nessuna promessa sul corpo"),
 ("Vincolo|CTA","Apri la tua prova da 14 giorni → https://t.me/giadacare_bot?start=ad_creatorsb2b_t14d"),
 ("Congedo","Provala per due settimane. Quando ti viene in mente quella cosa che racconteresti a un’amica, scrivimi."),
 ("Sticker","CI VEDIAMO NEL TUO VIDEO."),
]),
]
