# -*- coding: utf-8 -*-
# Blocchi del Manuale di volo v2 (18 pagine). kind = etichetta del ruolo nel layout.
P = [
("01","Copertina","Manuale di volo.",[
 ("Titolo","Manuale di volo."),
 ("Promessa","La tua voce. Una chat. Un video da ricordare."),
 ("Fumetto","Il tuo punto di vista conta."),
 ("Sticker","SI PARTE DA UN’IDEA · CIAO! · PROVA. IMMAGINA. CREA."),
 ("Footer","Il manuale per creare con Giada · VIVARIUM / SETTEMBRE 2026"),
]),
("02","Ciao","Sono Andrea.",[
 ("Titolo","Sono Andrea."),
 ("Presentazione","In Vivarium mi occupo di marketing e contenuti. Giada è la nostra assistente AI su Telegram: questo programma nasce da una cosa semplice, i video migliori li fa chi la usa e ha qualcosa da dire."),
 ("Patto","Non è un contest, né UGC a cottimo. Un video alla volta, pagato. Io porto obiettivi, riferimenti e limiti: idea, parole e taglio sono tuoi."),
 ("Chiusa","Le idee le leggo io, una per una. Qui c’è quello che darei a me stesso per cominciare."),
 ("Mappa","La tua mappa — 03 Conosci e prova Giada · 05 Trova la tua storia · 07 Esempi e mestiere · 13 Regole e consegna"),
 ("Sticker","18 PAGINE. DIECI MINUTI."),
]),
("03","Conosci Giada","Un’amica in chat. Un’assistente AI.",[
 ("Titolo","Un’amica in chat. Un’assistente AI."),
 ("Intro","Vive su Telegram. Le mandi testo, foto del piatto o vocali. Le puoi raccontare anche acqua, movimento, sonno e peso."),
 ("Funzione 1","Capire il pasto — Calorie e macro stimati, commento del piatto, coerenza con i tuoi obiettivi."),
 ("Funzione 2","Trovare cosa mangiare — Ricette con quello che hai in casa. Consigli pratici sulla dispensa."),
 ("Funzione 3","Tenere il filo — Feedback nel tempo e aiuto a riprendere dopo uno sgarro, senza sensi di colpa."),
 ("Funzione 4","Muoversi e uscire — Calorie attive e coaching. Al ristorante legge il menù che le mandi."),
 ("Vincolo|Disclaimer","Le stime sono indicative. Giada non è un medico né un nutrizionista: non fa diagnosi, non cura, non scrive diete."),
]),
("04","Prova Giada","Prima la chat. Poi la scintilla.",[
 ("Titolo","Prima la chat. Poi la scintilla."),
 ("Intro","Nei tuoi 7 giorni di prova usala davvero. Nessun compito da consegnare: tre spunti per scoprire quanto le puoi raccontare."),
 ("Spunto 1","«Cosa preparo con quello che ho in frigo?»"),
 ("Spunto 2","«Stasera mangio qui: mi dai un’idea dal menù?»"),
 ("Spunto 3","«Oggi è andata così. Come riprendo il filo?»"),
 ("Chiusa","Foto, vocale, testo: prova tutti e tre. La tua chat vera è il materiale del video."),
 ("Vincolo|CTA","Inizia i tuoi 7 giorni → https://t.me/giadacare_bot?start=ad_creatorsb2b_t7d (bottone + QR, stesso link)"),
]),
("05","A chi parli","Una persona. Un momento vero.",[
 ("Titolo","Una persona. Un momento vero."),
 ("Intro","Cinque situazioni, non cinque recinti. Scegline una e riconoscila nella tua esperienza."),
 ("Persona 01","La testa già piena — «Non ho voglia di pensarci anche a questo.» Evita “basta organizzarsi” e le lezioni di meal prep."),
 ("Persona 02","Il piano c’è. La costanza? — «So cosa fare. È farlo ogni giorno.» Evita di spiegare le basi a chi le conosce già."),
 ("Persona 03","Una presenza, senza etichette — «Voglio una risposta, non una lezione.» Mai “alla tua età”, mai “sei sola”."),
 ("Persona 04","I passi sì. E il pranzo? — «Misuro tutto, tranne quello che mangio.» Niente promesse di performance sportive."),
 ("Persona 05","Il solito “da lunedì” — «Non voglio ricominciare sempre da capo.» Niente colpa, niente disciplina, niente chili."),
 ("Nota","Persona non è targeting: scegli una situazione e parla solo a quella."),
]),
("06","Il video","Fai pensare: «Voglio provarla».",[
 ("Titolo","Fai pensare: «Voglio provarla»."),
 ("Intro","Il tuo video ha due vite: inserzione e reel o TikTok organico. Gira quello che pubblicheresti sul tuo profilo."),
 ("Mossa 1","Ferma lo scroll — Primi 3 secondi: una situazione precisa, un gesto, una domanda."),
 ("Mossa 2","Mostra il meccanismo — Giada in scena almeno un momento. Ingrandisci la chat: deve leggersi."),
 ("Mossa 3","Lascia un invito — Una CTA soft, una sola: «Provala gratuitamente dal link»."),
 ("Riquadro","Perché uno resta fino alla fine: SI RICONOSCE · VUOLE SAPERE COME FINISCE · VUOLE TENERLO · RICONOSCE TE"),
]),
("07","Esempi / Elena e Maria","Cosa abbiamo già fatto.",[
 ("Titolo","Cosa abbiamo già fatto."),
 ("Intro","Sei video nostri, quattro qui e due dopo. Prendi un’idea di regia e portala altrove: non cerco cloni."),
 ("Card","ELENA 1 · 61,5 s — Una domanda in mano. Da portare con te: fai coincidere le parole con un gesto visibile."),
 ("Card","ELENA 2 · 78,1 s — L’elenco tiene il filo. Da portare con te: il ritmo può stare nella struttura."),
 ("Card","MARIA 1 · 55,1 s — Un dubbio concreto. Da portare con te: mostra cosa succede dopo averle scritto."),
 ("Card","MARIA 2 · 55,9 s — Si vede la conversazione. Da portare con te: nascondi le altre conversazioni."),
 ("Nota","Nella cartella materiali: elena 1 / elena 2 / maria 1 / maria 2 - 1080.mp4"),
]),
("08","Esempi / Rosa","Altri due. Altra vita.",[
 ("Titolo","Altri due. Altra vita."),
 ("Intro","Rosa porta la giornata dentro il video. Guarda il taglio, non il contenuto."),
 ("Card","ROSA 1 · 65,2 s — Una giornata raccontata. Allenamento, piatti, luoghi veri: Giada entra nella quotidianità. Da portare con te: prendi la logica del vlog, scegli un momento vicino a chi ti guarda."),
 ("Card","ROSA 2 · 35,4 s — Poche scene, ben scelte. Colazione, luce, dettagli. Un racconto breve con un’estetica riconoscibile. Da portare con te: la chat deve leggersi, trentacinque secondi bastano."),
 ("Vincolo|Riquadro","Ispirazione, mai copia. Alcuni di questi esempi mostrano chat di terzi, marchi o schermi illeggibili: oggi si evitano. Nella cartella materiali: rosa 1 / rosa 2 - 1080.mp4"),
]),
("09","Scrivi l’idea","Uno script che respira.",[
 ("Titolo","Uno script che respira."),
 ("Intro","Inizio, centro, fine. In 30-90 secondi apri una tensione, fai arrivare la risposta e chiudi il cerchio. Scrivi in blocchi: per ogni frase decidi anche cosa si vede."),
 ("Chip","01 Apri una tensione · 02 Fai arrivare la risposta · 03 Chiudi il cerchio"),
 ("Script","HOOK — «Stasera ceno fuori. Il menù lo apro prima.» Si vede: tavolo e menù."),
 ("Script","COSTRUZIONE — «Lo mando a Giada, l’assistente AI su Telegram.» Si vede: il messaggio nella tua chat."),
 ("Script","PAYOFF — Mostra la risposta vera e cosa ti serve. Si vede: la parte di chat che lo dimostra."),
 ("Script","CTA — «Puoi provarla gratuitamente dal link.» Si vede: un invito breve e leggibile."),
 ("Nota","Prima di girare: l’esempio è inventato, riscrivilo con la tua esperienza. E controlla: la risposta arriva troppo presto?"),
]),
("10","Il primo fotogramma","Fermare lo scroll. Senza urlare.",[
 ("Titolo","Fermare lo scroll. Senza urlare."),
 ("Intro","Forme da provare, non frasi da recitare. Una sola tensione per video: scrivine tre sulla carta e tieni quella che regge."),
 ("Hook 01","Domanda sul piatto — «Cosa manca a questo pranzo?» Cibo dall’alto, domanda in alto."),
 ("Hook 02","Oggetto fuori posto — Un menù fra gli attrezzi della palestra. Una piccola incongruenza apre la storia."),
 ("Hook 03","Confronto di processo — Passi registrati / pasti ancora da raccontare. Confronta abitudini, mai corpi o chili."),
 ("Hook 04","Negazione — «Oggi niente conti a memoria.» Mostra subito il gesto alternativo."),
 ("Hook 05","Quiz — «Secondo te, cosa le ho chiesto?» Un dettaglio da scoprire nella chat."),
 ("Hook 06","Situazione riconoscibile — Frigo aperto. «E adesso?» Entra in scena senza presentazioni."),
 ("Hook 07","Parola gigante — «CENA?» sopra un’immagine vera. Una parola forte, poi la dimostrazione."),
 ("Hook 08","Metafora visiva — La lista delle cose da fare si allunga. Una scena semplice rende visibile il carico."),
]),
("11","Formato e montaggio","Il tuo taglio. Tre passate.",[
 ("Titolo","Il tuo taglio. Tre passate."),
 ("Intro","Volto e voce, voice-over, mani, cibo, registrazione dello schermo: il formato lo scegli tu. Poi monta in tre giri."),
 ("Formati","Chat protagonista · Problema → soluzione · Titolo da notizia · Risposta a un commento · Esperienza personale · Giornata / backstage"),
 ("Passata 01","Pulisci — Taglia partenze sbagliate e silenzi. Parti dal materiale che si può usare."),
 ("Passata 02","Tieni il punto — Se ti annoi guardandolo, accorcia proprio lì. Niente spazio morto."),
 ("Passata 03","Dai enfasi — Un piccolo zoom, una chat in sovrimpressione. Gli effetti devono chiarire."),
 ("Nota","Il ritmo è un motivo per restare. Nient’altro."),
]),
("12","Audio e sottotitoli","Si deve sentire. Si deve leggere.",[
 ("Titolo","Si deve sentire. Si deve leggere."),
 ("Audio","L’audio conta più del video. Registra vicino al microfono, in una stanza senza rimbombo. Riascolta: voce chiara, niente rumori sopra."),
 ("Vincolo|Musica","Musica: solo free e usabile in ads. Niente audio trending preso dai social. La licenza deve coprire pubblicità e tutti i canali. Nel dubbio, solo la tua voce."),
 ("Sottotitoli","Sottotitoli obbligatori. Stile libero. Due modi che funzionano, lo stile è tuo: maiuscolo + box (più contrasto) oppure parola accentata (leggero: controlla il contrasto)."),
 ("Nota","Prova in muto sul telefono. Tieni le parole lontane dal fondo e dai pulsanti laterali dei social."),
]),
("13","Le regole tecniche","La scheda da tenere a vista.",[
 ("Titolo","La scheda da tenere a vista."),
 ("Riquadri","9:16 verticale · 30-90 secondi"),
 ("Tabella","Lingua: italiano. Strumenti: qualsiasi, per ripresa e montaggio. Audio: perfetto, prima di tutto la voce. Sottotitoli: obbligatori, stile libero. Giada: almeno un momento, con chat leggibile. File: finito, senza watermark o loghi di editing. Invio: Drive o WeTransfer, niente girato grezzo. Tempi: 7-10 giorni dalla call. Revisione: massimo una; se funziona, nessuna."),
 ("Nota","Prima collaborazione: un video. Eventuali extra si concordano in call."),
]),
("14","Cosa non si può dire","Creatività sì. Promesse magiche no.",[
 ("Titolo","Creatività sì. Promesse magiche no."),
 ("Vincolo|Divieto","Niente promesse di chili, taglie o percentuali. Nessun risultato sul corpo garantito. Puoi mostrare numeri di processo reali."),
 ("Vincolo|Divieto","Niente primi piani su una parte del corpo. Non pizzicare grasso, non usare il corpo come problema da correggere."),
 ("Vincolo|Divieto","Niente frasi che attaccano l’aspetto. Anche il tuo. “Ero uno schifo” non va: nessuno deve sentirsi inferiore."),
 ("Vincolo|Divieto","Non dire “sei sola”. Non sfruttare solitudine o vulnerabilità. Mostra che Giada risponde."),
 ("Vincolo|Divieto","Dichiara: “assistente AI su Telegram”. In ogni contenuto. La relazione è amichevole, la natura del prodotto chiara."),
 ("Vincolo|Divieto","Non presentare Giada come nutrizionista. Non è un medico, non fa diagnosi, non cura. Nessuna condizione clinica nel video."),
 ("Nota","Resta dentro ciò che hai provato e che puoi mostrare nella tua chat."),
]),
("15","Cosa non si mostra","Un ultimo sguardo prima di esportare.",[
 ("Titolo","Un ultimo sguardo prima di esportare."),
 ("Vincolo|01","Solo la chat con Giada — Non mostrare la lista chat di Telegram, nomi, notifiche o dati di altre persone."),
 ("Vincolo|02","Nessun altro marchio in campo — Controlla vestiti, confezioni e sfondo. Niente watermark delle app di editing."),
 ("Vincolo|03","Niente minori — Se compare un altro adulto serve il suo consenso, e te ne assumi la responsabilità."),
 ("Vincolo|04","Niente audio trending — Prendilo da una libreria free con licenza valida per la pubblicità."),
 ("Nota","E ricorda l’ordine: prima l’idea, poi l’approvazione e la call. Solo dopo si gira."),
]),
("16","Come si va avanti","La tua idea arriva qui.",[
 ("Titolo","La tua idea arriva qui."),
 ("Indirizzo","andrea@vivariumai.co"),
 ("Intro","Mandami script e indicazioni visive in un documento, oppure un video-selfie su Drive. Dimmi persona, scena, apertura e cosa mostrerai di Giada. Nessuna scadenza."),
 ("Step 01","Entro 72 ore dall’idea — Ti rispondo con un riscontro, eventuali modifiche o una proposta di call breve."),
 ("Step 02","Idea approvata? Facciamo una call. — Allineiamo taglio, compenso e dettagli. Se passi questo step, estendo Giada di altri 14 giorni."),
 ("Step 03","Ora si gira. Poi si consegna. — Video finito entro 7-10 giorni dalla call, via Drive o WeTransfer. Massimo una revisione."),
 ("Avviso","Non girare prima dell’ok e della call. Un video mai richiesto non entra nel compenso."),
]),
("17","I soldi","Partiamo da qui. Poi ne parliamo.",[
 ("Titolo","Partiamo da qui. Poi ne parliamo."),
 ("Compenso","da 50€ per ogni video selezionato. È UN PAVIMENTO, NON UN TETTO."),
 ("Diritti","L’uso è incluso: campagne Giada e nostri canali, senza limite di tempo. Nessuna esclusiva: puoi lavorare con chi vuoi."),
 ("Upside","Cosa può far salire la cifra: hook aggiuntivi, pacchetti di video, collaborazione mensile, inserzioni dal tuo profilo (whitelisting), oppure accordi sulla performance se hai risultati da mostrare."),
 ("Riquadro","Si concorda in call, prima di girare. Due hook = due video finiti, con visivi diversi. Fattura o ritenuta d’acconto: ne parliamo lì."),
]),
("18","Ora tocca a te","Ultimo check. Poi tocca a te.",[
 ("Titolo","Ultimo check. Poi tocca a te."),
 ("Checklist","La scena parla a una persona precisa · Apertura e finale si tengono insieme · Giada si vede e la chat si legge · Dico “assistente AI su Telegram” · Audio chiaro, sottotitoli leggibili · Nessun divieto saltato"),
 ("Vincolo|CTA","Apri la prova creator → https://t.me/giadacare_bot?start=ad_creatorsb2b_t7d"),
 ("Indirizzo","andrea@vivariumai.co"),
 ("Congedo","Provala per una settimana. Quando ti viene in mente la cosa che racconteresti, scrivimi."),
 ("Sticker","CI VEDIAMO NELLA TUA IDEA."),
]),
]
